### ISSUE TITLE
感谢作者

### ISSUE THREAD

**Issue by pengchengma** [DSXiangLi/DecryptPrompt#1]
作者真棒！期待实时更新，以及增加更多模型评论和模型选择方面的内容，感谢🌹🌹🌹

**Comment by DSXiangLi** [comment]
thanks~ 会经常更新，不过会和我在看的paper方向相关，不会全面更新所有，模型评论我看到的话会加进来~

**Comment by liuhuanyong** [comment]
特别棒的工作！

**Comment by DreamingFuture** [comment]
真的太棒了！

**Comment by DSXiangLi** [comment]
> 特别棒的工作！

哈哈一直有follow您的公众号

**Comment by illusions-LYY** [comment]
面对大量的信息洪流，作者是怎么跟上LLM发展的呢？感觉总有无限的新方向和新算法出现，追不完的知识啊，作者效率太高了

**Comment by DSXiangLi** [comment]
> 面对大量的信息洪流，作者是怎么跟上LLM发展的呢？感觉总有无限的新方向和新算法出现，追不完的知识啊，作者效率太高了

还好每天固定留2-3个小时就够了，你想1天看1篇1年能看365，是不是超厉害！我一般早上1-2个小时读，晚上1-2个小时写。焦虑很正常，毕竟全世界nlper在写，你一个在读，这producer和consumer它不均衡，肯定积压，债多了不愁不怕~

**Comment by yyyiron** [comment]
感谢作者的工作，您的成果0给我的研究思想带来了很大的启发！
